server:
  port: 9001
spring:
  application:
    name: tensquare-base  #指定服务名
  datasource:
    url: jdbc:mysql://10.87.27.77:3306/tensquare_base?serverTimezone=CTT&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true