server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zjianru/tensquare_config.git
      label: master
  rabbitmq:
    host: 10.87.27.77
management: # 暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh